config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # main job of the routes: you map a request to a controller with an action
  get "/hello" => "welcome#index"
  get "/about" => "welcome#about"

  # providing the :as option will give us a route helper method
  # it will override the default one, if any; only loop the path portion
  # of the route, not the HTTP verbs
  # helper methods must be unique
  get "/hello/:name" => "welcome#greet", as: :greet

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  # get "/questions/new" => "questions#new", as: :new_question
  # post "/questions" => "questions#create", as: :questions
  # get "/questions/:id" => "questions#show", as: :question
  # get "/questions/:id/edit" => "questions#edit", as: :edit_question
  # patch "/questions/:id" => "questions#update"
  # delete "/questions/:id" => "questions#destroy"

  resources :questions do
    # use on collection when not targeting particular record
    get   :search,    on: :collection
    # use on member when targeting particular record of type question
    patch :mark_done, on: :member
    # use nothing when targeting antoher record not the question itself
    post  :approve

    # by defining resources :answers nested inside resources questions, Rails
    # will define all the answers route prepended with /questions/question_id
    # this enables us to have the question_id handy so we can create the answer
    # associated with a question with question_id
    resources :answers, only: [:create, :edit, :update, :destroy, :index]

    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :favorites, only: [:index]

  # do this to avoid triple nesting comments under resources :answers within
  # the resources :questions, as it will be very cumbersome to generate routes
  # and use forms; we don't need another set of answers routes in here, so
  # we pass the only: [] option to it
  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end
  # # can use the same path for this one as the one we used for questions#create
  # get "/questions" => "questions#index"

  # this does everything above.
  resources :questions
  root "welcome#index"

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create]
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  # this will map any GET request with path "/hello" to WelcomeController and
  # index action within that controller

  # every user request in Rails must be handled by a controller and action - action is method within the controller

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessor :tweet_it #to make an attribute accessible if not in the model

  belongs_to :category
  belongs_to :user
  # this will establish a has many association with answer. this assumes that your answer model has a question_id integer field
  # that references the question. with has_many, answers must be plural
  # must pass a dependent option to maintain data integrity; pass it :destroy or :nullify
  # destroy: delete all assoc. answers when you delete a question
  # nullify: if delete a question, updates the question_id of answers to NULL
  has_many :answers, dependent: :destroy
  # joins tables - comments has a many to one relationsip with answers
  has_many :comments, through: :answers

  has_many :likes, dependent: :destroy
  # establishes many to many relationship through likes; does a SQL join statement to connect tables
  has_many :users, through: :likes

  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user

  # this will fail validation (so it won't create or save) if the title is not provided and if it is not unique
  validates :title, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 255 }
  # set custom message for error
  # DSL: Domain Specific Lanugage
  validates :body, uniqueness: { message: "must be unique"}

  # this validates that the combination of the title and body is unique. Which means that the title doesn't have to be unique by itself, however, the combo of the two fields must be unique
  # validates :title, uniqueness: {scope: :body}

  validates :view_count, numericality: {greater_than_or_equal_to: 0}

  # validates :email,
  #           format: { with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }

  # using custom validation method; must make sure that 'no_monkey' is a method available for our class. The method can be public or private; more likely we'll have it as a private method because we don't need to use it outside this class.
  validate :no_monkey

  # callback method
  after_initialize :set_defaults

  # scope :recent, lambda {order ("created_at DESC").limit(5)}
  # is the same as:
  def self.recent(number = 5)
    order("created_at DESC").limit(number)
  end

  def self.search(term)
    where(["title || body ILIKE ?", "%#{term}%"]).order("view_count DESC")
  end

  def self.call
    view_count += 1
  end

  def category_name
    category.name if category
  end

  # prefix means you call it with user_full_name - prefix it with the model
  # delegate :full_name, to: :user, prefix: true
  def user_full_name
    user.full_name if user
  end

  def like_for(user)
    likes.find_by_user_id user
  end

  def favorite_for(user)
    favorites.find_by_user_id user
  end

  def tag_names
    tags.map {|tag| tag.name}
  end

  def vote_for(user)
    votes.find_by_user_id user
  end

  def vote_result
    votes.up_count - votes.down_count
  end

  private

  def set_defaults
    self.view_count ||= 0
  end

  def no_monkey
    if title && title.downcase.include?("monkey")
      errors.add(:title, "No monkey!!!")
    end
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::BaseController

  def index
    @questions = Question.order("created_at DESC").limit(10)
    render json: @questions
  end

  def show
    @question = Question.find params[:id]
    render json: @question
  end

  def create
    question_params = params.require(:question).permit(:title, :body)
    @question = Question.new question_params
    @question.user = @user
    if @question.save
      head :ok
    else
      render json: { errors: @question.errors.full_messages }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # runs find_question before any action so we don't have to find the question over and over
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def new
    @question = Question.new
    # can set default values here that will show up automatically in the form - good for repopulating fields
  end

  def create
    # using params.require ensures that there is a key called question in my params; the permit method will only allow parameters that you explicitly list; in this case, title and body
    @question = Question.new question_params
    @question.user = current_user
    if @question.save
      if @question.tweet_it
        client = Twitter::REST::Client.new do |config|
          config.consumer_key        = ENV["twitter_consumer_key"]
          config.consumer_secret     = ENV["twitter_consumer_secret"]
          config.access_token        = "YOUR_ACCESS_TOKEN"
          config.access_token_secret = "YOUR_ACCESS_SECRET"
        end
        client.update("New Question: #{@question.title}")
      end
      redirect_to question_path(@question)
    else
      # this will render app/views/questions/new.html.erb template
      # we need to be explicit about rendering the new template because the default behavior is to render 'create.html.erb'
      render :new
    end
  end

  def show
    @question.view_count += 1
    @question.save
    @answer = Answer.new
    @answers = @question.answers
    respond_to do |format|
      format.html { render }
      format.json { render json: @question }
    end
  end

  def index
    @questions = Question.all
    respond_to do |format|
      format.html { render }
      format.json { render json: @questions.select(:id, :title, :view_count) }
    end
  end

  def edit
  end

  def update
    if @question.update question_params
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :category_id, :tweet_it, {tag_ids: []})
  end

  def find_question
    @question = Question.find params[:id]
  end

  def authorize_user
    unless can? :manage, @question
      redirect_to root_path, alert: "access denied!"
    end
  end
end

app/helpers/api/v1/questions_helper.rb
module Api::V1::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<% if !@question.errors.empty? %>
<div class="alert alert-danger"><%= @question.errors.full_messages.join(", ") %></div>
<% end %>

<%# for_for takes in an ActiveRecord object as a first argument. then it looks at the object. if the object is not persisted (not yet saved to db) The form will automatically use POST for its method. it will also automatically use 'questions_path' as its action (convention is that the questions_path will submit to the 'create' action) %>
<%= form_for @question do |f| %>
  <%# we call 'f' the form object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.check_box :tweet_it %> Tweet It!
  </div>
  <div class="form-group">
    <%#= To assign a value to a foreign key using a dropdown menu  %>
    <%= f.label :category_id %>
    <%= f.collection_select(:category_id, Category.order("name"), :id, :name, html: {class: "form-control"}) %>
  </div>
  <div class="form-group">
    <%= f.collection_check_boxes(:tag_ids, Tag.order("name"), :id, :name) %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1>All Questions (<%= @questions.count %>)</h1>

<table width="100%" class="table table-striped">
  <% @questions.order("id").each do |question| %>
    <tr>
      <td><%= link_to question.title, question_path(question) %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<h3>Category: <%= @question.category_name%></h3>
<p>Created by: <%= @question.user_full_name %></p>

<p><%= @question.body %></p>

<p><%= @question.created_at %></p>

<p>View Count:
  <%= @question.view_count %>
</p>
<p>Likes: <%= @question.likes.count %></p>
<p>Favorites: <%= @question.favorites.count %></p>
<p>Tags: <%= @question.tag_names.join(", ")%></p>
<hr>

<% vote = @question.vote_for(current_user) %>
<% if !vote %>
  <%= link_to fa_icon("arrow-up"), question_votes_path(@question, {vote: {is_up: true}}), method: :post, style: "font-size: 35px;" %>
  (<%= @question.vote_result %>)
  <%= link_to fa_icon("arrow-down"), question_votes_path(@question, {vote: {is_up: false}}), method: :post, style: "font-size: 35px;" %>
<% elsif vote.is_up? %>
  <%= link_to fa_icon("times"), question_vote_path(@question, vote), method: :delete, style: "font-size: 35px;" %>
  (<%= @question.vote_result %>)
  <%= link_to fa_icon("arrow-down"), question_vote_path(@question, vote, {vote: {is_up: false}}), method: :patch, style: "font-size: 35px;" %>
<% else %>
  <%= link_to fa_icon("arrow-up"), question_vote_path(@question, vote, {vote: {is_up: true}}), method: :patch, style: "font-size: 35px;" %>
  (<%= @question.vote_result %>)
  <%= link_to fa_icon("times"), question_vote_path(@question, vote), method: :delete, style: "font-size: 35px;" %>
<% end %>

<div id="question-like">
  <%= render "/likes/question_like" %>
</div>

<div id="question-favorite">
  <%= render "/favorites/question_favorite" %>
</div>

<% if can? :edit, @question %>
<%= link_to "Edit", edit_question_path(@question) %>
<% end %>

<% if can? :destroy, @question %>
<%= link_to "Delete", question_path(@question), method: :delete, data: {confirm: "Are you sure"} %>
<% end %>

<h3>Create an Answer</h3>

<% if can? :create, Answer %>
<div id="answer-form">
  <%= render "/answers/form" %>
</div>
<% end %>

<h2>Answers</h2>

<div class="answers">
  <% @question.answers.each do |answer|%>
    <%= render "/answers/answer", answer: answer %>
  <% end %>
</div>

<%# we can use the form after overriding th url parameter. the downside to it
is that it own't work for edit situation - only for create. so we can't
reuse it if we decide to implement editing answers %>
<%#= form_for @answer, url: question_answers_path(@question) do |f| %>
<%# end %>

<%# passing an arry to the form_for is a better approach for creating nested
resources. this approach will work for both new and edit situations. so if
@answer is not persisted it will send a POST request to
question_answers_path(@question). and if @answer is persisted it will send a
PATCH request to question_answer_path(@question, @answer)  %>
<%#= form_for [@question, @answer], remote: true do |f| %>
  <!-- <div> -->
    <%#= f.label :body %>
    <%#= f.text_area :body %>
  <!-- </div> -->
  <%#= f.submit %>
<%# end %>