config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # main job of the routes: you map a request to a controller with an action
  get "/hello" => "welcome#index"
  get "/about" => "welcome#about"

  # providing the :as option will give us a route helper method
  # it will override the default one, if any; only loop the path portion
  # of the route, not the HTTP verbs
  # helper methods must be unique
  get "/hello/:name" => "welcome#greet", as: :greet

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  # get "/questions/new" => "questions#new", as: :new_question
  # post "/questions" => "questions#create", as: :questions
  # get "/questions/:id" => "questions#show", as: :question
  # get "/questions/:id/edit" => "questions#edit", as: :edit_question
  # patch "/questions/:id" => "questions#update"
  # delete "/questions/:id" => "questions#destroy"

  resources :questions do
    # use on collection when not targeting particular record
    get   :search,    on: :collection
    # use on member when targeting particular record of type question
    patch :mark_done, on: :member
    # use nothing when targeting antoher record not the question itself
    post  :approve

    # by defining resources :answers nested inside resources questions, Rails
    # will define all the answers route prepended with /questions/question_id
    # this enables us to have the question_id handy so we can create the answer
    # associated with a question with question_id
    resources :answers, only: [:create, :edit, :update, :destroy, :index]

    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :favorites, only: [:index]

  # do this to avoid triple nesting comments under resources :answers within
  # the resources :questions, as it will be very cumbersome to generate routes
  # and use forms; we don't need another set of answers routes in here, so
  # we pass the only: [] option to it
  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end
  # # can use the same path for this one as the one we used for questions#create
  # get "/questions" => "questions#index"

  # this does everything above.
  resources :questions
  root "welcome#index"

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create]
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  # this will map any GET request with path "/hello" to WelcomeController and
  # index action within that controller

  # every user request in Rails must be handled by a controller and action - action is method within the controller

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :user_id, :question_id, presence: true
  validates :user_id, uniqueness: {scope: :question_id}

  def question_title
    question.title
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user

  def index
    @questions = current_user.favorite_questions
  end

  def create
    @question = Question.find params[:question_id]
    @favorite = Favorite.new(question: @question, user: current_user)
    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @question, notice: "Question saved to favorites!" }
        format.js { render :successfully_favorited}
      else
        format.html { redirect_to @question, alert: "Question not saved to favorites!" }
        format.js { render :unsuccessfully_favorited}
      end
    end
  end

  def destroy
    session[:return_to] ||= request.referer
    @question = Question.find params[:question_id]
    @favorite = current_user.favorites.find params[:id]
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to session.delete(:return_to), alert: "Question deleted from favorites!" }
      format.js   { render }
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_question_favorite.html.erb
<% favorite = @question.favorite_for(current_user) %>
<% if favorite %>
<%#= link_to (raw("<span class='glyphicon glyphicon-remove' style='font-size:30px'></span>")), question_favorite_path(@question, favorite), method: :delete %>
<%= link_to fa_icon("heart"), question_favorite_path(@question, favorite),
                              method: :delete,
                              remote: true,
                              style: "font-size: 35px;" %>
<% else %>
<%#= link_to (raw("<span class='glyphicon glyphicon-heart' style='font-size:30px'></span>")), question_favorites_path(@question), method: :post %>
<%= link_to fa_icon("heart-o"), question_favorites_path(@question),
                                method: :post,
                                remote: true,
                                style: "font-size: 35px;" %>
<% end %>
<hr>

app/views/favorites/destroy.js.erb
$('#question-favorite').html("<%= j render 'question_favorite' %>")

app/views/favorites/index.html.erb
<h1>Favorite Questions</h1>

<% @questions.each do |question| %>
<p>
<%= link_to "#{question.title}", question_path(question)%>
<%#= link_to (raw("<span class='glyphicon glyphicon-remove' style='font-size:12px;'></span>")), question_favorite_path(question, question.user_id), method: :delete %>
</p>
<% end %>

app/views/favorites/successfully_favorited.js.erb
$('#question-favorite').html("<%= j render 'question_favorite' %>")

app/views/favorites/unsuccessfully_favorited.js.erb
alert("Can't favorite, may have been favorited already!");