config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # main job of the routes: you map a request to a controller with an action
  get "/hello" => "welcome#index"
  get "/about" => "welcome#about"

  # providing the :as option will give us a route helper method
  # it will override the default one, if any; only loop the path portion
  # of the route, not the HTTP verbs
  # helper methods must be unique
  get "/hello/:name" => "welcome#greet", as: :greet

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  # get "/questions/new" => "questions#new", as: :new_question
  # post "/questions" => "questions#create", as: :questions
  # get "/questions/:id" => "questions#show", as: :question
  # get "/questions/:id/edit" => "questions#edit", as: :edit_question
  # patch "/questions/:id" => "questions#update"
  # delete "/questions/:id" => "questions#destroy"

  resources :questions do
    # use on collection when not targeting particular record
    get   :search,    on: :collection
    # use on member when targeting particular record of type question
    patch :mark_done, on: :member
    # use nothing when targeting antoher record not the question itself
    post  :approve

    # by defining resources :answers nested inside resources questions, Rails
    # will define all the answers route prepended with /questions/question_id
    # this enables us to have the question_id handy so we can create the answer
    # associated with a question with question_id
    resources :answers, only: [:create, :edit, :update, :destroy, :index]

    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :favorites, only: [:index]

  # do this to avoid triple nesting comments under resources :answers within
  # the resources :questions, as it will be very cumbersome to generate routes
  # and use forms; we don't need another set of answers routes in here, so
  # we pass the only: [] option to it
  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end
  # # can use the same path for this one as the one we used for questions#create
  # get "/questions" => "questions#index"

  # this does everything above.
  resources :questions
  root "welcome#index"

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create]
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  # this will map any GET request with path "/hello" to WelcomeController and
  # index action within that controller

  # every user request in Rails must be handled by a controller and action - action is method within the controller

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :body, presence: true, uniqueness: {scope: :question_id}

  def user_full_name
    user.full_name if user
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_answer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def create
    @question = Question.find params[:question_id]
    @answer = Answer.new answer_params
    @answer.question = @question
    @answer.user = current_user
    respond_to do |format|
      if @answer.save
        # AnswersMailer.notify_question_owner(@answer).deliver_later
        # indicates what to do if in html format
        format.html { redirect_to question_path(@question), notice: "Answer created!" }
        # indicates what to do if in js format
        format.js   { render :create_success }
      else
        format.html { render "/questions/show", alert: "Answer not created!" }
        format.js   { render :create_failure }
      end
    end
  end

  def edit
    @question = @answer.question
  end

  def index
    @question = Question.find params[:question_id]
    render json: @question.answers
  end

  def update
    if @answer.update answer_params
      redirect_to question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_path(params[:question_id]), notice: "Answer deleted!"}
      format.js { render } # this renders app/views/answers/destroy.js.erb
    end
  end

  private

  def find_answer
    @answer = Answer.find params[:id]
  end

  def answer_params
    params.require(:answer).permit(:body, :question_id, :user_id)
  end

  def authorize_user
    unless (can? :manage, @answer) || (can? :destroy, @answer)
      redirect_to root_path, alert: "access denied!"
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<%# dom_id generates an id that can be used on the page that helpers identify this div uniquely
will be in the format model_name_id - e.g. answer_4 %>

<div id="<%= dom_id(answer) %>">
  <%= answer.body %><br>
  Created by: <%= answer.user_full_name %><br>
  <% if can? :edit, answer %>
  <%= link_to "Edit", edit_question_answer_path(@question, answer) %>
  <% end %>

  <% if can? :destroy, answer %>
  <%= link_to "Delete", question_answer_path(@question, answer), method: :delete, remote: true, data: {confirm: "Are you sure"} %>
  <% end %>
  <hr>
</div>

app/views/answers/_form.html.erb
<%= @answer.errors.full_messages.join(", ") %>

<%= form_for [@question, @answer], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/answers/create_failure.js.erb
// this re-renders the form within its containing div if there is an error -
// the re-rendering picks up the errors and displays them 
$("#answer-form").html("<%= j render 'form' %>");

app/views/answers/create_success.js.erb
// j is a helper methdo from Rails to escape the JS so it doesn't break with quotes or new line characters
$('.answers').prepend('<%= j render "answer", answer: @answer %>')
// clears the input field for creating an answer
// $('#answer_body').val("");

// create a new answer because it persisted from the previous if there were errors; but we want to create a new answer
// rather than update existing
<% @answer = Answer.new %>
$("#answer-form").html("<%= j render 'form' %>");

app/views/answers/destroy.js.erb
$("#<%= dom_id(@answer) %>").fadeOut(1000, function(){ $(this).remove(); });

app/views/answers/edit.html.erb
<h1>Edit Answer</h1>

<%= render "form" %>

<div class="btn my-btn btn-primary" style="width:100px; margin-top:20px;">Click Me</div>
<input type="text" id="my-box">
<div id="output"></div>