config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # main job of the routes: you map a request to a controller with an action
  get "/hello" => "welcome#index"
  get "/about" => "welcome#about"

  # providing the :as option will give us a route helper method
  # it will override the default one, if any; only loop the path portion
  # of the route, not the HTTP verbs
  # helper methods must be unique
  get "/hello/:name" => "welcome#greet", as: :greet

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  # get "/questions/new" => "questions#new", as: :new_question
  # post "/questions" => "questions#create", as: :questions
  # get "/questions/:id" => "questions#show", as: :question
  # get "/questions/:id/edit" => "questions#edit", as: :edit_question
  # patch "/questions/:id" => "questions#update"
  # delete "/questions/:id" => "questions#destroy"

  resources :questions do
    # use on collection when not targeting particular record
    get   :search,    on: :collection
    # use on member when targeting particular record of type question
    patch :mark_done, on: :member
    # use nothing when targeting antoher record not the question itself
    post  :approve

    # by defining resources :answers nested inside resources questions, Rails
    # will define all the answers route prepended with /questions/question_id
    # this enables us to have the question_id handy so we can create the answer
    # associated with a question with question_id
    resources :answers, only: [:create, :edit, :update, :destroy, :index]

    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :favorites, only: [:index]

  # do this to avoid triple nesting comments under resources :answers within
  # the resources :questions, as it will be very cumbersome to generate routes
  # and use forms; we don't need another set of answers routes in here, so
  # we pass the only: [] option to it
  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end
  # # can use the same path for this one as the one we used for questions#create
  # get "/questions" => "questions#index"

  # this does everything above.
  resources :questions
  root "welcome#index"

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create]
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  # this will map any GET request with path "/hello" to WelcomeController and
  # index action within that controller

  # every user request in Rails must be handled by a controller and action - action is method within the controller

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ask Amy</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
      initMap = function() {
        var myLocation =  new google.maps.LatLng(49.282270, -123.108509);

        var mapProp = {
          center:         myLocation,
          zoom:           17,
          scrollwheel:    false,
          draggable:      false,
          mapTypeId:      google.maps.MapTypeId.ROADMAP
          };

        var mapDiv =      document.getElementById('map');
        var map =         new google.maps.Map(mapDiv, mapProp);

        var marker =      new google.maps.Marker({
          position:       myLocation,
          icon:           'https://maps.google.com/mapfiles/kml/shapes/schools_maps.png'
        });
        marker.setMap(map);

        var infowindow =  new google.maps.InfoWindow({content:"CodeCore"});
        infowindow.open(map,marker);
      }

      google.maps.event.addDomListener(window, 'load', initMap);

    </script>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">

<!-- <a href="/hello">Hello</a> |
<a href="/about">About</a> | -->
<%# hello_path & about_path are called route helpers. They get generated from
    the content of `routes.rb` and they are methods that can be used in
    all view files and all controllers %>
<!-- <a href="<%= hello_path %>">Hello</a> |
<a href="<%= about_path %>">About</a> |
<a href="<%= greet_path('Kaia') %>">Greet Kaia</a> | -->
<!-- put in hash if you have to pass it multiple params later on -->
<!-- <a href="<%= greet_path({name: 'John'}) %>">Greet John</a> | -->

<!-- <%= link_to "Hello", hello_path %> | -->
<!-- <%#= link_to "Subscribe", subscribe_path %> | -->
<!-- <%#= link_to "All Questions", questions_path %> | -->
<!-- <%#= link_to "New Question", new_question_path %> | -->

<%# if user_signed_in? %>
  <!-- Hello <%#= current_user.first_name %> | -->
  <!-- <%#= link_to "Log Out", sessions_path, method: :delete, data: {confirm: "Are you sure"} %> | -->
<%# else %>
  <!-- <%#= link_to "Log In", new_session_path %> | -->
  <!-- <%#= link_to "Sign Up", new_user_path %> | -->
<%# end %>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <a href="#" class="navbar-left"><%= image_tag "logo.png" %></a>
    <!-- <a href="#" class="navbar-left navbar-brand">Awesome Answers</a> -->
    <%= link_to "Ask Amy", hello_path, class: "navbar-left navbar-brand" %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "About", about_path%></li>
      <li><%= link_to "Greet Kaia", greet_path('Kaia') %></li>
      <li><%= link_to "All Questions", questions_path %> </li>
      <li><%= link_to "New Question", new_question_path %></li>
      <% if user_signed_in? %>
        <li><a href="#">Hello <%= current_user.first_name %></a></li>
        <li><%= link_to "Favorites", favorites_path %></li>
        <li><%= link_to "Log Out", sessions_path, method: :delete, data: {confirm: "Are you sure"} %></li>
      <% else %>
        <li><%= link_to "Log In", new_session_path %></li>
        <li><%= link_to "Log In with Twitter", sign_in_with_twitter_path %></li>
        <li><%= link_to "Sign Up", new_user_path %></li>
      <% end %>
    </ul>
  </div>
</nav>
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<% if alert %>
  <div class="alert alert-danger"><%= alert %></div>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <%= yield %>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <a href="#"><i class="fa fa-facebook"></i></a>
  <a href="#"><i class="fa fa-twitter"></i></a>
  <a href="#"><i class="fa fa-linkedin"></i></a>
  <a href="#"><i class="fa fa-google"></i>+</a>
  <p>&copy; 2016, Created by Kaia Olson</p>
</footer>
</body>
</html>